version: '3.8'

services:
  backend:
    image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/openjdk:17-8.6
    container_name: springboot-app
    volumes:
      - ./app.jar:/app/app.jar:ro
      - ./data:/app/data
    working_dir: /app
    command: ["java", "-jar", "app.jar","--server.port=18080"]
    expose:
      - "18080"          # 仅对内网（Nginx）暴露，不对外
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    user: "0:0"   # 以 root 身份运行（UID 0）
    container_name: nginx-proxy
    ports:
      - "18081:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge